### ISSUE TITLE
Support "This Anime Does Not Exist" StyleGAN2 model by aydao/gwern for anime image generation

### ISSUE THREAD

**Issue by n00mkrad** [galatolofederico/clip-glass#1]
Website: https://thisanimedoesnotexist.ai/

The model can be downloaded here: https://www.gwern.net/Faces#tadne-download

Considering GLaSS already supports BigGAN and different SG2 models, I hope it wouldn't be too hard to add this great model too.

**Comment by galatolofederico** [comment]
Thank you for the suggestion 😊
Yes i guess it should be easy.
In the next days I am a bit busy but next weekend I will add it.

**Comment by galatolofederico** [comment]
Hey, i had some free time today and i looked into TADNE
It seems that TADNE is written in tensorflow using the original stylegan implementation. 
I've tried to convert the weights using the  pytorch stylegan implementation that i've used to develop GLaSS (which is: https://github.com/Tetratrio/stylegan2_pytorch ) but unfortunately it fails. Maybe it will work using this other implementation https://github.com/rosinality/stylegan2-pytorch but last time i tried it i had a lot of problems related to the nvcc compiler (it is a known issue with archlinux apparently)
But since GLaSS only uses the forward pass it is possibile to mix pytorch and tensorflow models. I dont want to refactor the code too much so i need to think about how to integrate the stylegan2 tensorflow model with minimal impact to the code

**Comment by Poopsikins** [comment]
Any progress on this?

**Comment by galatolofederico** [comment]
No sorry I am busy with other projects at the moment
